name: OpenWebUI Frontend
version: "0.1.0"
slug: openwebui_frontend
description: A Home Assistant addon for the OpenWebUI frontend.
arch:
  - amd64
  - aarch64
url: "https://github.com/Sangoku/home_asistant_open_webui"
startup: application
init: false
ports:
  8080/tcp: 3000 # Map the container's 8080 to host port 3000
ports_description:
  8080/tcp: Web interface
ingress: true
ingress_port: 3000
image: "ghcr.io/open-webui/open-webui:main" # We will build our own image based on this
options:
  gpu_enabled: false
  gpu_type: "nvidia" # or "amd", etc.
schema:
  gpu_enabled: bool
  gpu_type: str
